### ISSUE TITLE
NOVA Core Snapshot API Not Downloadable

### ISSUE THREAD

**Issue by Temmie19** [NOVA-Team/NOVA-Core#308] opened 2017-07-27 23:15 UTC
Currently, for whatever reason, the sites at which the source for the snapshots are down and are currently unable to download the files needed to start up any project.

**Comment by Temmie19** [comment] 2017-07-27 23:23
Can we just get a download for it elsewhere?

**Comment by ExE-Boss** [comment] 2017-10-21 12:05
Duplicate of #208

**Closed by ExE-Boss** 2017-10-21 12:05 UTC
